import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    "nav.search": "Buscar",
    "nav.whoAreYou": "¿Quién sos?",
    "nav.forStudents": "Para Estudiantes",
    "nav.forParents": "Para Padres",
    "nav.forResidences": "Para Residencias",
    "nav.publishResidence": "Publicar residencia",
    "nav.menu": "Menú",
    "nav.login": "Ingresar",
    "nav.back": "← Volver",
    
    // Hero
    "hero.title": "Tu hogar universitario\nempieza con confianza",
    "hero.subtitle": "Viví, estudiá y crecé en una comunidad segura, conectada y transparente",
    
    // Trust Badges
    "trust.verified.title": "Residencias y Perfiles Verificados",
    "trust.verified.description": "Validamos todas las residencias y usuarios",
    "trust.availability.title": "Disponibilidad Real",
    "trust.availability.description": "Información actualizada en tiempo real",
    "trust.benefits.title": "Beneficios Exclusivos",
    "trust.benefits.description": "Descuentos y premios por puntos",
    
    // Search Bar
    "search.location": "Ubicación",
    "search.roomType": "Tipo de habitación",
    "search.roomType.individual": "Habitación individual",
    "search.roomType.shared": "Habitación compartida",
    "search.roomType.apartment": "Apartamento Compartido",
    "search.capacity": "Capacidad",
    "search.capacity.double": "Doble",
    "search.capacity.triple": "Triple",
    "search.capacity.quadruple": "Cuádruple",
    "search.capacity.quintuple": "Quintuple",
    "search.filters": "Filtros",
    "search.advancedFilters": "Filtros avanzados",
    "search.refineSearch": "Refiná tu búsqueda con características específicas",
    "search.button": "Buscar",
    "search.applyFilters": "Aplicar filtros",
    "search.roommateRating": "Calificación mínima de compañeros",
    "search.residenceRating": "Calificación mínima de residencia",
    
    // Filters
    "filter.coordinator": "Coordinador Presencial",
    "filter.kitchen": "Cocina Equipada",
    "filter.laundry": "Lavandería",
    "filter.livingRoom": "Sala de Estar",
    "filter.cameras": "Cámaras de Seguridad",
    "filter.studyRoom": "Sala de Estudio",
    "filter.desk": "Escritorio Personal en Hab.",
    "filter.locker": "Locker de guardado",
    "filter.cleaning": "Limpieza en Habitaciones",
    "filter.ownerManaged": "Atendida por dueños",
    "filter.privateBathroom": "Baño Privado x Hab",
    "filter.balcony": "Balcón",
    "filter.pets": "Acepta Mascotas",
    "filter.ac": "Aire Acondicionado",
    
    // Profile Selector
    "profile.title": "¿Quién sos?",
    "profile.subtitle": "Seleccioná tu perfil para acceder a beneficios exclusivos y una experiencia personalizada",
    "profile.student": "Estudiante",
    "profile.student.subtitle": "Encontrá tu hogar ideal",
    "profile.student.benefit1": "Buscá residencias verificadas",
    "profile.student.benefit2": "Conocé a tus futuros compañeros",
    "profile.student.benefit3": "Sistema de puntos y descuentos",
    "profile.student.benefit4": "Acceso a recursos exclusivos",
    "profile.parent": "Padre/Madre",
    "profile.parent.subtitle": "Seguridad para tu hijo/a",
    "profile.parent.benefit1": "Residencias verificadas y seguras",
    "profile.parent.benefit2": "Comunidad de padres",
    "profile.parent.benefit3": "Comunicación directa con residencias",
    "profile.parent.benefit4": "Beneficios en hoteles y transporte",
    "profile.residence": "Residencia",
    "profile.residence.subtitle": "Gestioná tu propiedad",
    "profile.residence.benefit1": "PMS integrado y gratuito",
    "profile.residence.benefit2": "Disponibilidad en tiempo real",
    "profile.residence.benefit3": "Acceso a miles de estudiantes",
    "profile.residence.benefit4": "Descuentos en servicios",
    "profile.mainBenefits": "Ventajas principales:",
    "profile.hide": "Ocultar",
    "profile.showDetails": "Ver detalles",
    "profile.seeMore": "Ver más",
    
    // Featured Residences
    "residences.title": "Residencias destacadas",
    "residences.subtitle": "Las mejores opciones verificadas para vos",
    "residences.viewAll": "Ver todas →",
    "residences.viewAllMobile": "Ver todas las residencias",
    "residences.verified": "Verificada",
    "residences.residents": "residentes",
    "residences.meetRoommates": "Conocé a tus compañeros",
    "residences.viewRoom": "Ver habitación",
    "residences.viewDetails": "Ver detalles",
    "residences.perMonth": "/mes",
    "residences.pts": "pts",
    
    // How it works
    "howItWorks.title": "¿Cómo funciona?",
    "howItWorks.subtitle": "Encontrá tu hogar universitario en 4 simples pasos",
    "howItWorks.step1.title": "Explorá",
    "howItWorks.step1.description": "Buscá residencias verificadas en tu ciudad universitaria",
    "howItWorks.step2.title": "Conectá",
    "howItWorks.step2.description": "Conocé a tus futuros compañeros antes de reservar",
    "howItWorks.step3.title": "Reservá",
    "howItWorks.step3.description": "Confirmá tu lugar de forma segura y transparente",
    "howItWorks.step4.title": "Sumá puntos",
    "howItWorks.step4.description": "Ganá beneficios por buena convivencia y referencias",
    
    // CTA Section
    "cta.title": "¿Tenés una residencia estudiantil?",
    "cta.subtitle": "Sumá tu residencia a nuestra plataforma y conectá con miles de estudiantes que buscan un hogar confiable",
    "cta.contact": "Contactanos",
    "cta.learnMore": "Conocé más",
    
    // Footer
    "footer.tagline": "Tu hogar universitario empieza con confianza. Viví, aprendé y crecé en una comunidad segura y conectada.",
    "footer.forStudents": "Para Estudiantes",
    "footer.searchResidences": "Buscar residencias",
    "footer.createProfile": "Crear perfil",
    "footer.premiumBenefits": "Beneficios Premium",
    "footer.resources": "Recursos",
    "footer.forResidences": "Para Residencias",
    "footer.registerResidence": "Registrar residencia",
    "footer.managementPanel": "Panel de gestión",
    "footer.pricing": "Precios",
    "footer.support": "Soporte",
    "footer.followUs": "Síguenos",
    "footer.rights": "© 2025 Sin Fronteras. Todos los derechos reservados.",
    
    // Login Dialog
    "login.title": "Ingresar",
    "login.selectProfile": "Seleccioná tu tipo de perfil para continuar",
    "login.student.description": "Accedé a tu perfil de estudiante",
    "login.parent.description": "Accedé a tu perfil de padre",
    "login.residence.description": "Accedé al panel de gestión",
    
    // 404 Page
    "notFound.title": "404",
    "notFound.message": "¡Ups! Página no encontrada",
    "notFound.returnHome": "Volver al inicio",
    
    // AI Assistant
    "assistant.title": "Asistente de Búsqueda",
    "assistant.placeholder": "¿Qué tipo de residencia buscas?",
    "assistant.send": "Enviar",
    "assistant.welcome": "¡Hola! Soy tu asistente para encontrar la residencia perfecta.",
    "assistant.welcomeHint": "Pregúntame sobre ubicaciones, tipos de habitación o amenidades.",

    // Student Profile Page
    "student.hero.title": "Portal para Estudiantes",
    "student.hero.subtitle": "Encontrá tu residencia ideal, conectá con compañeros y accedé a recursos exclusivos",
    "student.behavior.title": "Tu Comportamiento También Cuenta",
    "student.behavior.subtitle": "Los rankings no son sólo para las residencias. Tu comportamiento tiene puntaje y beneficios.",
    "student.behavior.howItWorks": "¿Cómo Funciona Tu Puntuación?",
    "student.behavior.howItWorksDesc": "Tu puntuación es un mix entre las valoraciones de tus compañeros pasados o actuales, y la valoración de las residencias hacia vos.",
    "student.behavior.concepts": "Conceptos de Convivencia Valorados:",
    "student.behavior.order": "Orden",
    "student.behavior.cleanliness": "Limpieza",
    "student.behavior.interactions": "Interacciones",
    "student.behavior.empathy": "Empatía",
    "student.behavior.tolerance": "Tolerancia",
    "student.behavior.personality": "Forma de ser",
    "student.behavior.profileDecision": "Tu Perfil, Tu Decisión:",
    "student.behavior.profileDecisionDesc": "Cada estudiante escribe en su perfil lo que quiere para describirse, y elige qué muestra y qué no al público.",
    "student.behavior.profileTip": "💡 Mientras más completes y muestres tu perfil:",
    "student.behavior.profileBenefit1": "Mejores beneficios obtenés",
    "student.behavior.profileBenefit2": "Más probable es que consigas compañeros acorde a tus características",
    "student.behavior.profileBenefit3": "Mayor confianza generás en residencias y otros estudiantes",
    "student.behavior.residenceEval": "Evaluación de las Residencias:",
    "student.behavior.residenceEvalDesc": "Las residencias también completan un perfil de cada estudiante. Los llamados de atención o expulsiones influyen en el puntaje, apareciendo únicamente la advertencia en cada perfil, pero no el detalle de lo sucedido. Esto mantiene tu privacidad mientras asegura transparencia en la comunidad.",
    "student.points.title": "Sistema de Puntos y Badges",
    "student.points.subtitle": "Ganá beneficios mientras ayudás a la comunidad",
    "student.badges.title": "Niveles de Badges",
    "student.badges.benefits": "Beneficios:",
    "student.resources.title": "Recursos para Estudiantes",
    "student.resources.subtitle": "Aprovechá todas las herramientas disponibles para tu vida universitaria",
    "student.resources.explore": "Explorar",
    "student.coexistence.title": "Normas de Convivencia Básicas",
    "student.coexistence.subtitle": "Principios fundamentales para una convivencia armoniosa",
    "student.coexistence.respect.title": "Respeto Mutuo",
    "student.coexistence.respect.desc": "Respetá los horarios de estudio y descanso de tus compañeros. La empatía es clave para una buena convivencia.",
    "student.coexistence.communication.title": "Comunicación Clara",
    "student.coexistence.communication.desc": "Hablá abiertamente sobre expectativas y necesidades. La comunicación previene conflictos.",
    "student.coexistence.responsibility.title": "Responsabilidad Compartida",
    "student.coexistence.responsibility.desc": "Participá en la limpieza y mantenimiento de espacios comunes. Todos somos responsables del entorno.",
    
    // Student Badges
    "student.badge.novice": "Novato",
    "student.badge.novice.req": "0-100 puntos",
    "student.badge.novice.desc": "Estás comenzando tu camino. Completá tu perfil y realizá tu primera evaluación.",
    "student.badge.novice.benefit1": "Acceso básico al portal",
    "student.badge.novice.benefit2": "Búsqueda de residencias",
    "student.badge.bronze": "Bronce",
    "student.badge.bronze.req": "100-300 puntos",
    "student.badge.bronze.desc": "¡Buen comienzo! Ya tenés evaluaciones positivas y tu perfil está completo.",
    "student.badge.bronze.benefit1": "10% descuento en primera reserva",
    "student.badge.bronze.benefit2": "Prioridad en respuestas",
    "student.badge.silver": "Plata",
    "student.badge.silver.req": "300-600 puntos",
    "student.badge.silver.desc": "Excelente convivencia. Tus compañeros y residencias te valoran positivamente.",
    "student.badge.silver.benefit1": "15% descuento",
    "student.badge.silver.benefit2": "Badge visible en perfil",
    "student.badge.silver.benefit3": "Acceso a eventos exclusivos",
    "student.badge.gold": "Oro",
    "student.badge.gold.req": "600-1000 puntos",
    "student.badge.gold.desc": "Sos un ejemplo de convivencia. Tu comportamiento es destacado en la comunidad.",
    "student.badge.gold.benefit1": "20% descuento",
    "student.badge.gold.benefit2": "Prioridad en reservas",
    "student.badge.gold.benefit3": "Acceso VIP a nuevas residencias",
    "student.badge.platinum": "Platino",
    "student.badge.platinum.req": "1000+ puntos",
    "student.badge.platinum.desc": "¡Nivel máximo! Sos referente en la comunidad y tu perfil es ejemplo para otros.",
    "student.badge.platinum.benefit1": "25% descuento permanente",
    "student.badge.platinum.benefit2": "Programa de embajador",
    "student.badge.platinum.benefit3": "Beneficios premium de por vida",
    
    // Student Resources
    "student.resource.tutoring.title": "Tutorías y Apoyo Académico",
    "student.resource.tutoring.desc": "Conectá con tutores verificados o ofrecé tu ayuda a otros estudiantes",
    "student.resource.coexistence.title": "Guía de Convivencia",
    "student.resource.coexistence.desc": "Aprendé las mejores prácticas para una convivencia armoniosa",
    "student.resource.ratings.title": "Sistema de Calificaciones",
    "student.resource.ratings.desc": "Entendé cómo funcionan las reseñas y calificaciones entre compañeros",
    "student.resource.studentResources.title": "Recursos Estudiantiles",
    "student.resource.studentResources.desc": "Descuentos en cursos, gimnasios, eventos y más beneficios exclusivos",

    // Parent Profile Page
    "parent.hero.title": "Portal para Padres",
    "parent.hero.subtitle": "Acompañá a tu hijo/a con tranquilidad y seguridad. Conectá con la comunidad y accedé a recursos exclusivos.",
    "parent.hero.joinCommunity": "Unirme a la Comunidad Premium",
    "parent.hero.viewResidences": "Ver Residencias Verificadas",
    "parent.privacy.title": "Privacidad y Seguridad",
    "parent.privacy.desc": "Tu perfil está vinculado al de tu hijo/a mediante verificación de DNI. Por motivos de privacidad, podrás contactar con otros padres pero no con estudiantes directamente.",
    "parent.privacy.access": "Tendrás acceso completo a:",
    "parent.privacy.access1": "Información de residencias y documentación legal",
    "parent.privacy.access2": "Foro de padres y grupos de discusión privados",
    "parent.privacy.access3": "Comunicación directa con las residencias",
    "parent.privacy.access4": "Perfil y evaluaciones de tu hijo/a",
    "parent.privacy.policy": "Ver Política de Privacidad",
    "parent.verification.title": "Proceso de Verificación de Residencias",
    "parent.verification.subtitle": "Garantizamos la calidad y seguridad de cada residencia en nuestra plataforma",
    "parent.verification.visits.title": "Visitas Personales",
    "parent.verification.visits.desc": "Recorremos personalmente todas las residencias y corroboramos las instalaciones y servicios ofrecidos.",
    "parent.verification.responsible.title": "Conocemos a los Responsables",
    "parent.verification.responsible.desc": "Nos reunimos con dueños y coordinadores para asegurar compromiso con la calidad y bienestar estudiantil.",
    "parent.verification.feedback.title": "Feedback de Estudiantes",
    "parent.verification.feedback.desc": "Hablamos con estudiantes actuales para obtener feedback honesto sobre cada residencia.",
    "parent.verification.improvements.title": "Plan de Mejoras",
    "parent.verification.improvements.desc": "Implementamos un plan de mejoras y otorgamos sugerencias para aumentar la calidad de cada establecimiento.",
    "parent.community.badge": "COMUNIDAD",
    "parent.community.title": "Comunidad de Padres",
    "parent.community.subtitle": "Conectá con otros padres que están pasando por la misma experiencia. Compartí consejos, preocupaciones y soluciones.",
    "parent.community.forum.title": "Foro de Discusión",
    "parent.community.forum.desc": "Participá en conversaciones sobre alojamiento, seguridad y experiencias universitarias",
    "parent.community.events.title": "Eventos y Encuentros",
    "parent.community.events.desc": "Conocé a otros padres en eventos organizados cuando visitás a tu hijo/a",
    "parent.community.discounts.title": "Descuentos Exclusivos",
    "parent.community.discounts.desc": "Accedé a descuentos en hoteles, transporte y servicios para tus visitas",
    "parent.points.title": "Sistema de Puntos y Badges",
    "parent.points.subtitle": "Ganá beneficios mientras ayudás a otros padres y participás en la comunidad",
    "parent.badges.title": "Niveles de Membresía",
    "parent.evaluation.title": "Sistema de Evaluación y Confianza",
    "parent.evaluation.subtitle": "Entendé cómo funciona el sistema de rankings que protege a tu hijo/a",
    "parent.evaluation.rankings.title": "Rankings: Más allá de las Residencias",
    "parent.evaluation.rankings.desc": "Los rankings no son sólo para las residencias. Los estudiantes también son evaluados.",
    "parent.resources.title": "Recursos para Padres",
    "parent.resources.subtitle": "Todo lo que necesitás para acompañar a tu hijo/a en esta etapa",
    "parent.disclaimer.title": "⚠️ Importante",
    "parent.disclaimer.text": "Sin Fronteras es una plataforma de conexión y gestión. No somos intermediarios financieros ni responsables directos del funcionamiento de las residencias. Nuestra función es verificar, conectar y facilitar la comunicación entre todas las partes.",

    // Parent Badges
    "parent.badge.newMember": "Nuevo Miembro",
    "parent.badge.newMember.req": "0-50 puntos",
    "parent.badge.newMember.desc": "Bienvenido a la comunidad. Comenzá participando y conociendo otros padres.",
    "parent.badge.newMember.benefit1": "Acceso a foro básico",
    "parent.badge.newMember.benefit2": "Visualización de residencias verificadas",
    "parent.badge.collaborator": "Colaborador",
    "parent.badge.collaborator.req": "50-150 puntos",
    "parent.badge.collaborator.desc": "Ya participás activamente en la comunidad compartiendo experiencias.",
    "parent.badge.collaborator.benefit1": "5% descuento en eventos",
    "parent.badge.collaborator.benefit2": "Acceso a grupos privados",
    "parent.badge.collaborator.benefit3": "Newsletter mensual",
    "parent.badge.active": "Miembro Activo",
    "parent.badge.active.req": "150-350 puntos",
    "parent.badge.active.desc": "Tu participación es valiosa. Ayudás a otros padres con tus consejos.",
    "parent.badge.active.benefit1": "10% descuento en hoteles",
    "parent.badge.active.benefit2": "Invitaciones a eventos premium",
    "parent.badge.active.benefit3": "Asesoría prioritaria",
    "parent.badge.expert": "Experto",
    "parent.badge.expert.req": "350-600 puntos",
    "parent.badge.expert.desc": "Sos referente en la comunidad. Tus aportes son muy valorados.",
    "parent.badge.expert.benefit1": "15% descuento permanente",
    "parent.badge.expert.benefit2": "Moderador de grupos",
    "parent.badge.expert.benefit3": "Acceso VIP a recursos",
    "parent.badge.ambassador": "Embajador",
    "parent.badge.ambassador.req": "600+ puntos",
    "parent.badge.ambassador.desc": "Nivel máximo. Representás lo mejor de nuestra comunidad de padres.",
    "parent.badge.ambassador.benefit1": "20% descuento de por vida",
    "parent.badge.ambassador.benefit2": "Eventos exclusivos",
    "parent.badge.ambassador.benefit3": "Participación en decisiones de la plataforma",

    // Parent Resources
    "parent.resource.community.title": "Comunidad de Padres",
    "parent.resource.community.desc": "Conectá con otros padres, compartí experiencias y obtené consejos",
    "parent.resource.security.title": "Guía de Seguridad",
    "parent.resource.security.desc": "Todo lo que necesitás saber sobre la seguridad de tu hijo/a",
    "parent.resource.behavior.title": "Manual de Comportamiento",
    "parent.resource.behavior.desc": "Normas y reglamentos de las residencias estudiantiles",
    "parent.resource.discounts.title": "Descuentos y Beneficios",
    "parent.resource.discounts.desc": "Acceso a descuentos en hoteles, transporte y servicios turísticos",
    "parent.resource.communication.title": "Comunicación con Residencias",
    "parent.resource.communication.desc": "Contacto directo y transparente con las residencias",
    "parent.resource.support.title": "Recursos de Apoyo",
    "parent.resource.support.desc": "Guías prácticas para ayudar a tu hijo/a en su vida universitaria",

    // Residence PMS Page
    "pms.badge": "SISTEMA DE GESTIÓN PROFESIONAL",
    "pms.hero.title": "PMS para Residencias Estudiantiles",
    "pms.hero.subtitle": "Profesionalizá tu residencia con nuestro sistema de gestión completo. Todo lo que necesitás en una sola plataforma.",
    "pms.hero.demo": "Solicitar Demo Gratuita",
    "pms.hero.pricing": "Ver Precios",
    "pms.features.title": "Funcionalidades del PMS",
    "pms.features.subtitle": "Todo lo que necesitás para gestionar tu residencia de forma profesional",
    "pms.features.students.title": "Gestión de Estudiantes",
    "pms.features.students.desc": "Registrá y administrá toda la información de tus residentes",
    "pms.features.payments.title": "Control de Pagos",
    "pms.features.payments.desc": "Seguimiento automático de pagos, cuotas y moratorias",
    "pms.features.maintenance.title": "Mantenimiento",
    "pms.features.maintenance.desc": "Gestión de incidencias y solicitudes de mantenimiento",
    "pms.features.docs.title": "Documentación",
    "pms.features.docs.desc": "Almacenamiento seguro de contratos y documentos legales",
    "pms.features.reports.title": "Reportes y Estadísticas",
    "pms.features.reports.desc": "Análisis financiero y operativo en tiempo real",
    "pms.features.panel.title": "Panel Integrado",
    "pms.features.panel.desc": "Todo lo que necesitás en un solo lugar, fácil de usar",
    "pms.benefits.title": "Beneficios del Sistema",
    "pms.benefits.subtitle": "Transformá tu residencia con nuestra plataforma integral",
    "pms.benefits.sync.title": "Sincronización Automática",
    "pms.benefits.sync.desc": "Tu perfil público en el portal se actualiza automáticamente desde el PMS. Disponibilidad en tiempo real sin duplicar trabajo. Los estudiantes ven exactamente qué habitaciones están disponibles en cada momento.",
    "pms.benefits.visibility.title": "Mayor Visibilidad",
    "pms.benefits.visibility.desc": "Aparecé en las búsquedas de miles de estudiantes y padres verificados. Aumentá tu ocupación hasta 40% con nuestra base de usuarios activos buscando alojamiento.",
    "pms.benefits.reputation.title": "Sistema de Reputación",
    "pms.benefits.reputation.desc": "Mejorá tu posicionamiento con buenas calificaciones y ganá hasta 20% de descuento en tu plan mensual. Las residencias mejor calificadas aparecen primero en búsquedas.",
    "pms.benefits.support.title": "Soporte Dedicado 24/7",
    "pms.benefits.support.desc": "Equipo de soporte técnico disponible para ayudarte con cualquier duda o problema. Capacitación completa incluida y actualizaciones constantes sin costo adicional.",
    "pms.points.title": "Sistema de Puntos y Badges",
    "pms.points.subtitle": "Mejorá tu servicio y obtené descuentos significativos en tu plan mensual",
    "pms.badges.title": "Niveles de Certificación",
    "pms.evaluation.title": "Sistema de Evaluación Bidireccional",
    "pms.evaluation.subtitle": "En nuestra plataforma, no solo evaluás: también sos evaluado. Un sistema justo que beneficia a todos.",
    "pms.evaluation.improve.title": "Evaluá y Mejorá Continuamente",
    "pms.evaluation.improve.desc": "Los rankings no son sólo para las residencias. Los estudiantes también tienen puntuaciones basadas en su comportamiento y convivencia.",
    "pms.evaluation.howTo.title": "¿Cómo Evaluás a tus Residentes?",
    "pms.evaluation.howTo.desc": "Podés evaluar a cada estudiante en conceptos de convivencia. Tu opinión, junto con la de otros compañeros, forma la puntuación del estudiante:",
    "pms.evaluation.benefits.title": "Beneficios del Sistema",
    "pms.evaluation.forResidence": "Para tu Residencia:",
    "pms.evaluation.forResidence1": "Atraé estudiantes responsables y verificados",
    "pms.evaluation.forResidence2": "Reducí conflictos con información previa",
    "pms.evaluation.forResidence3": "Mejorá tu reputación con evaluaciones positivas",
    "pms.evaluation.forStudents": "Para los Estudiantes:",
    "pms.evaluation.forStudents1": "Conocen la calidad de tu residencia antes de reservar",
    "pms.evaluation.forStudents2": "Sistema justo basado en experiencias reales",
    "pms.evaluation.forStudents3": "Incentivo para mantener buena convivencia",
    "pms.warnings.title": "Gestión de Advertencias Mejorada",
    "pms.warnings.desc": "Si hay un problema serio con un residente, podés registrar advertencias en su perfil:",
    "pms.warnings.feature1": "La advertencia queda visible para otras residencias",
    "pms.warnings.feature2": "El detalle del incidente permanece privado",
    "pms.warnings.feature3": "Los padres reciben notificación de la advertencia",
    "pms.warnings.feature4": "Sistema de escalado para casos graves",
    "pms.warnings.note": "Este sistema protege tu residencia y la comunidad, manteniendo la privacidad del estudiante mientras se comunica información relevante.",
    "pms.resources.title": "Recursos Adicionales",
    "pms.resources.subtitle": "Accedé a proveedores verificados y servicios exclusivos para tu residencia",
    "pms.resources.providers.title": "Proveedores Verificados",
    "pms.resources.providers.desc": "Accedé a proveedores confiables de limpieza, mantenimiento y servicios",
    "pms.resources.accounting.title": "Asesoría Contable",
    "pms.resources.accounting.desc": "Recursos contables y fiscales para gestionar tu residencia",
    "pms.resources.hr.title": "Recursos Humanos",
    "pms.resources.hr.desc": "Guías para contratar personal y gestionar equipos",
    "pms.resources.practices.title": "Buenas Prácticas",
    "pms.resources.practices.desc": "Aprendé de las mejores residencias y mejorá continuamente",
    "pms.cta.title": "¿Listo para profesionalizar tu residencia?",
    "pms.cta.subtitle": "Unite a la red de residencias verificadas y accedé a miles de estudiantes buscando alojamiento",
    "pms.cta.demo": "Solicitar Demo Gratuita",
    "pms.cta.contact": "Contactar Equipo de Ventas",

    // PMS Badges
    "pms.badge.initial": "Inicial",
    "pms.badge.initial.req": "0-100 puntos",
    "pms.badge.initial.desc": "Nueva residencia en la plataforma. Comenzá a construir tu reputación.",
    "pms.badge.initial.benefit1": "Publicación básica",
    "pms.badge.initial.benefit2": "Sin descuentos en plan",
    "pms.badge.bronze": "Bronce",
    "pms.badge.bronze.req": "100-300 puntos | 4.0+ ★",
    "pms.badge.bronze.desc": "Buenas primeras evaluaciones. Tus residentes están satisfechos.",
    "pms.badge.bronze.benefit1": "5% descuento en plan mensual",
    "pms.badge.bronze.benefit2": "Badge visible",
    "pms.badge.bronze.benefit3": "Prioridad en búsquedas",
    "pms.badge.silver": "Plata",
    "pms.badge.silver.req": "300-600 puntos | 4.3+ ★",
    "pms.badge.silver.desc": "Excelente reputación. Gestión profesional reconocida por la comunidad.",
    "pms.badge.silver.benefit1": "10% descuento permanente",
    "pms.badge.silver.benefit2": "Destacado en resultados",
    "pms.badge.silver.benefit3": "Soporte prioritario",
    "pms.badge.gold": "Oro",
    "pms.badge.gold.req": "600-1000 puntos | 4.6+ ★",
    "pms.badge.gold.desc": "Residencia de referencia. Calidad superior en todos los aspectos.",
    "pms.badge.gold.benefit1": "15% descuento",
    "pms.badge.gold.benefit2": "Sección 'Destacadas'",
    "pms.badge.gold.benefit3": "Acceso a programa embajador",
    "pms.badge.platinum": "Platino",
    "pms.badge.platinum.req": "1000+ puntos | 4.8+ ★",
    "pms.badge.platinum.desc": "Nivel de excelencia máximo. Modelo a seguir en la industria.",
    "pms.badge.platinum.benefit1": "20% descuento de por vida",
    "pms.badge.platinum.benefit2": "Publicidad premium gratis",
    "pms.badge.platinum.benefit3": "Participación en desarrollo de features",

    // All Residences Page
    "allResidences.available.title": "Residencias con Disponibilidad",
    "allResidences.available.subtitle": "Reservá ahora y asegurá tu lugar",
    "allResidences.unavailable.title": "Sin Disponibilidad Actual",
    "allResidences.unavailable.subtitle": "Anotate en la lista de espera para recibir notificaciones",
    "allResidences.unavailable.badge": "Sin Disponibilidad",
    "allResidences.viewInfo": "Ver información completa",
    "allResidences.notify": "Avisarme cuando haya lugar",
    "allResidences.waitlist.title": "Lista de Espera",
    "allResidences.waitlist.desc": "Te notificaremos cuando haya disponibilidad en",
    "allResidences.waitlist.tip.title": "💡 Consejo Importante",
    "allResidences.waitlist.tip.desc": "Completá tu perfil de estudiante para tener prioridad. Las residencias pueden elegir a qué estudiantes contactar según sus perfiles, así que asegurate de tener toda tu información actualizada.",
    "allResidences.waitlist.roomType": "Tipo de habitación de interés",
    "allResidences.waitlist.selectType": "Seleccionar tipo",
    "allResidences.waitlist.individual": "Individual",
    "allResidences.waitlist.double": "Doble",
    "allResidences.waitlist.triple": "Triple",
    "allResidences.waitlist.quadruple": "Cuádruple",
    "allResidences.waitlist.email": "Email de notificación",
    "allResidences.waitlist.join": "Unirme a la lista de espera",
    "allResidences.waitlist.success": "¡Te avisaremos cuando haya disponibilidad! Completá tu perfil para tener prioridad.",

    // Residence Details Page
    "details.verified": "Verificada",
    "details.reviews": "reseñas",
    "details.sendQuery": "Enviar consulta por chat",
    "details.book": "Reservar",
    "details.about.title": "Sobre la residencia",
    "details.services.title": "Servicios",
    "details.commonAreas.title": "Áreas comunes",
    "details.availability.title": "Disponibilidad de habitaciones",
    "details.room.male": "♂ Masculina",
    "details.room.female": "♀ Femenina",
    "details.room.available": "disponibles",
    "details.room.of": "de",
    "details.room.month": "/mes",
    "details.room.deposit": "+ Depósito",
    "details.room.enrollment": "+ Matrícula",
    "details.room.meetRoommates": "Conocé a tus compañeros",
    "details.room.viewProfile": "Ver perfil →",
    "details.room.emptyBed": "Cama disponible",
    "details.room.bookThisRoom": "Reservar esta habitación",
    "details.residents.title": "Todos los Residentes",
    "details.residents.viewAll": "Ver todos los residentes",
    "details.residents.current": "residentes actuales",
    "details.contact.title": "Información de contacto",
    "details.contact.phone": "Teléfono",
    "details.contact.phoneHidden": "Visible al reservar",
    "details.contact.address": "Dirección",
    "details.contact.addressHidden": "Visible al reservar",
    "details.contact.email": "Contacto",
    "details.booking.title": "Reservar Habitación",
    "details.chat.title": "Contactar Residencia",
  },
  en: {
    // Header
    "nav.search": "Search",
    "nav.whoAreYou": "Who are you?",
    "nav.forStudents": "For Students",
    "nav.forParents": "For Parents",
    "nav.forResidences": "For Residences",
    "nav.publishResidence": "Publish residence",
    "nav.menu": "Menu",
    "nav.login": "Login",
    "nav.back": "← Back",
    
    // Hero
    "hero.title": "Your university home\nstarts with trust",
    "hero.subtitle": "Live, study and grow in a safe, connected and transparent community",
    
    // Trust Badges
    "trust.verified.title": "Verified Residences and Profiles",
    "trust.verified.description": "We validate all residences and users",
    "trust.availability.title": "Real Availability",
    "trust.availability.description": "Real-time updated information",
    "trust.benefits.title": "Exclusive Benefits",
    "trust.benefits.description": "Discounts and rewards by points",
    
    // Search Bar
    "search.location": "Location",
    "search.roomType": "Room type",
    "search.roomType.individual": "Single room",
    "search.roomType.shared": "Shared room",
    "search.roomType.apartment": "Shared Apartment",
    "search.capacity": "Capacity",
    "search.capacity.double": "Double",
    "search.capacity.triple": "Triple",
    "search.capacity.quadruple": "Quadruple",
    "search.capacity.quintuple": "Quintuple",
    "search.filters": "Filters",
    "search.advancedFilters": "Advanced filters",
    "search.refineSearch": "Refine your search with specific features",
    "search.button": "Search",
    "search.applyFilters": "Apply filters",
    "search.roommateRating": "Minimum roommate rating",
    "search.residenceRating": "Minimum residence rating",
    
    // Filters
    "filter.coordinator": "On-site Coordinator",
    "filter.kitchen": "Equipped Kitchen",
    "filter.laundry": "Laundry",
    "filter.livingRoom": "Living Room",
    "filter.cameras": "Security Cameras",
    "filter.studyRoom": "Study Room",
    "filter.desk": "Personal Desk in Room",
    "filter.locker": "Storage Locker",
    "filter.cleaning": "Room Cleaning",
    "filter.ownerManaged": "Owner Managed",
    "filter.privateBathroom": "Private Bathroom",
    "filter.balcony": "Balcony",
    "filter.pets": "Pets Allowed",
    "filter.ac": "Air Conditioning",
    
    // Profile Selector
    "profile.title": "Who are you?",
    "profile.subtitle": "Select your profile to access exclusive benefits and a personalized experience",
    "profile.student": "Student",
    "profile.student.subtitle": "Find your ideal home",
    "profile.student.benefit1": "Search verified residences",
    "profile.student.benefit2": "Meet your future roommates",
    "profile.student.benefit3": "Points and discounts system",
    "profile.student.benefit4": "Access to exclusive resources",
    "profile.parent": "Parent",
    "profile.parent.subtitle": "Safety for your child",
    "profile.parent.benefit1": "Verified and safe residences",
    "profile.parent.benefit2": "Parent community",
    "profile.parent.benefit3": "Direct communication with residences",
    "profile.parent.benefit4": "Hotel and transport benefits",
    "profile.residence": "Residence",
    "profile.residence.subtitle": "Manage your property",
    "profile.residence.benefit1": "Free integrated PMS",
    "profile.residence.benefit2": "Real-time availability",
    "profile.residence.benefit3": "Access to thousands of students",
    "profile.residence.benefit4": "Service discounts",
    "profile.mainBenefits": "Main benefits:",
    "profile.hide": "Hide",
    "profile.showDetails": "Show details",
    "profile.seeMore": "See more",
    
    // Featured Residences
    "residences.title": "Featured Residences",
    "residences.subtitle": "The best verified options for you",
    "residences.viewAll": "View all →",
    "residences.viewAllMobile": "View all residences",
    "residences.verified": "Verified",
    "residences.residents": "residents",
    "residences.meetRoommates": "Meet your roommates",
    "residences.viewRoom": "View room",
    "residences.viewDetails": "View details",
    "residences.perMonth": "/month",
    "residences.pts": "pts",
    
    // How it works
    "howItWorks.title": "How does it work?",
    "howItWorks.subtitle": "Find your university home in 4 simple steps",
    "howItWorks.step1.title": "Explore",
    "howItWorks.step1.description": "Search verified residences in your university city",
    "howItWorks.step2.title": "Connect",
    "howItWorks.step2.description": "Meet your future roommates before booking",
    "howItWorks.step3.title": "Book",
    "howItWorks.step3.description": "Confirm your place safely and transparently",
    "howItWorks.step4.title": "Earn points",
    "howItWorks.step4.description": "Get benefits for good coexistence and referrals",
    
    // CTA Section
    "cta.title": "Do you have a student residence?",
    "cta.subtitle": "Add your residence to our platform and connect with thousands of students looking for a reliable home",
    "cta.contact": "Contact us",
    "cta.learnMore": "Learn more",
    
    // Footer
    "footer.tagline": "Your university home starts with trust. Live, learn and grow in a safe and connected community.",
    "footer.forStudents": "For Students",
    "footer.searchResidences": "Search residences",
    "footer.createProfile": "Create profile",
    "footer.premiumBenefits": "Premium Benefits",
    "footer.resources": "Resources",
    "footer.forResidences": "For Residences",
    "footer.registerResidence": "Register residence",
    "footer.managementPanel": "Management panel",
    "footer.pricing": "Pricing",
    "footer.support": "Support",
    "footer.followUs": "Follow us",
    "footer.rights": "© 2025 Sin Fronteras. All rights reserved.",
    
    // Login Dialog
    "login.title": "Login",
    "login.selectProfile": "Select your profile type to continue",
    "login.student.description": "Access your student profile",
    "login.parent.description": "Access your parent profile",
    "login.residence.description": "Access the management panel",
    
    // 404 Page
    "notFound.title": "404",
    "notFound.message": "Oops! Page not found",
    "notFound.returnHome": "Return to Home",
    
    // AI Assistant
    "assistant.title": "Search Assistant",
    "assistant.placeholder": "What type of residence are you looking for?",
    "assistant.send": "Send",
    "assistant.welcome": "Hi! I'm your assistant to find the perfect residence.",
    "assistant.welcomeHint": "Ask me about locations, room types, or amenities.",

    // Student Profile Page
    "student.hero.title": "Student Portal",
    "student.hero.subtitle": "Find your ideal residence, connect with roommates and access exclusive resources",
    "student.behavior.title": "Your Behavior Also Counts",
    "student.behavior.subtitle": "Rankings aren't just for residences. Your behavior has a score and benefits.",
    "student.behavior.howItWorks": "How Does Your Score Work?",
    "student.behavior.howItWorksDesc": "Your score is a mix between ratings from your past or current roommates, and the residence's rating of you.",
    "student.behavior.concepts": "Valued Coexistence Concepts:",
    "student.behavior.order": "Order",
    "student.behavior.cleanliness": "Cleanliness",
    "student.behavior.interactions": "Interactions",
    "student.behavior.empathy": "Empathy",
    "student.behavior.tolerance": "Tolerance",
    "student.behavior.personality": "Personality",
    "student.behavior.profileDecision": "Your Profile, Your Decision:",
    "student.behavior.profileDecisionDesc": "Each student writes what they want on their profile to describe themselves, and chooses what to show and what not to show publicly.",
    "student.behavior.profileTip": "💡 The more you complete and show your profile:",
    "student.behavior.profileBenefit1": "Better benefits you get",
    "student.behavior.profileBenefit2": "More likely to find roommates matching your characteristics",
    "student.behavior.profileBenefit3": "Greater trust you generate in residences and other students",
    "student.behavior.residenceEval": "Residence Evaluation:",
    "student.behavior.residenceEvalDesc": "Residences also complete a profile for each student. Warnings or expulsions affect the score, with only the warning appearing on each profile, but not the detail of what happened. This maintains your privacy while ensuring transparency in the community.",
    "student.points.title": "Points and Badges System",
    "student.points.subtitle": "Earn benefits while helping the community",
    "student.badges.title": "Badge Levels",
    "student.badges.benefits": "Benefits:",
    "student.resources.title": "Student Resources",
    "student.resources.subtitle": "Take advantage of all available tools for your university life",
    "student.resources.explore": "Explore",
    "student.coexistence.title": "Basic Coexistence Rules",
    "student.coexistence.subtitle": "Fundamental principles for harmonious coexistence",
    "student.coexistence.respect.title": "Mutual Respect",
    "student.coexistence.respect.desc": "Respect your roommates' study and rest schedules. Empathy is key to good coexistence.",
    "student.coexistence.communication.title": "Clear Communication",
    "student.coexistence.communication.desc": "Talk openly about expectations and needs. Communication prevents conflicts.",
    "student.coexistence.responsibility.title": "Shared Responsibility",
    "student.coexistence.responsibility.desc": "Participate in cleaning and maintaining common areas. We are all responsible for the environment.",
    
    // Student Badges
    "student.badge.novice": "Novice",
    "student.badge.novice.req": "0-100 points",
    "student.badge.novice.desc": "You're starting your journey. Complete your profile and make your first evaluation.",
    "student.badge.novice.benefit1": "Basic portal access",
    "student.badge.novice.benefit2": "Residence search",
    "student.badge.bronze": "Bronze",
    "student.badge.bronze.req": "100-300 points",
    "student.badge.bronze.desc": "Good start! You have positive evaluations and your profile is complete.",
    "student.badge.bronze.benefit1": "10% discount on first booking",
    "student.badge.bronze.benefit2": "Priority in responses",
    "student.badge.silver": "Silver",
    "student.badge.silver.req": "300-600 points",
    "student.badge.silver.desc": "Excellent coexistence. Your roommates and residences value you positively.",
    "student.badge.silver.benefit1": "15% discount",
    "student.badge.silver.benefit2": "Visible badge on profile",
    "student.badge.silver.benefit3": "Access to exclusive events",
    "student.badge.gold": "Gold",
    "student.badge.gold.req": "600-1000 points",
    "student.badge.gold.desc": "You're an example of coexistence. Your behavior is highlighted in the community.",
    "student.badge.gold.benefit1": "20% discount",
    "student.badge.gold.benefit2": "Priority in bookings",
    "student.badge.gold.benefit3": "VIP access to new residences",
    "student.badge.platinum": "Platinum",
    "student.badge.platinum.req": "1000+ points",
    "student.badge.platinum.desc": "Maximum level! You're a reference in the community and your profile is an example for others.",
    "student.badge.platinum.benefit1": "25% permanent discount",
    "student.badge.platinum.benefit2": "Ambassador program",
    "student.badge.platinum.benefit3": "Lifetime premium benefits",
    
    // Student Resources
    "student.resource.tutoring.title": "Tutoring and Academic Support",
    "student.resource.tutoring.desc": "Connect with verified tutors or offer your help to other students",
    "student.resource.coexistence.title": "Coexistence Guide",
    "student.resource.coexistence.desc": "Learn best practices for harmonious coexistence",
    "student.resource.ratings.title": "Rating System",
    "student.resource.ratings.desc": "Understand how reviews and ratings work between roommates",
    "student.resource.studentResources.title": "Student Resources",
    "student.resource.studentResources.desc": "Discounts on courses, gyms, events and more exclusive benefits",

    // Parent Profile Page
    "parent.hero.title": "Parent Portal",
    "parent.hero.subtitle": "Support your child with peace of mind and security. Connect with the community and access exclusive resources.",
    "parent.hero.joinCommunity": "Join Premium Community",
    "parent.hero.viewResidences": "View Verified Residences",
    "parent.privacy.title": "Privacy and Security",
    "parent.privacy.desc": "Your profile is linked to your child's through ID verification. For privacy reasons, you can contact other parents but not students directly.",
    "parent.privacy.access": "You'll have full access to:",
    "parent.privacy.access1": "Residence information and legal documentation",
    "parent.privacy.access2": "Parent forum and private discussion groups",
    "parent.privacy.access3": "Direct communication with residences",
    "parent.privacy.access4": "Your child's profile and evaluations",
    "parent.privacy.policy": "View Privacy Policy",
    "parent.verification.title": "Residence Verification Process",
    "parent.verification.subtitle": "We guarantee the quality and safety of each residence on our platform",
    "parent.verification.visits.title": "Personal Visits",
    "parent.verification.visits.desc": "We personally tour all residences and verify the facilities and services offered.",
    "parent.verification.responsible.title": "We Meet the Managers",
    "parent.verification.responsible.desc": "We meet with owners and coordinators to ensure commitment to quality and student well-being.",
    "parent.verification.feedback.title": "Student Feedback",
    "parent.verification.feedback.desc": "We talk with current students to get honest feedback about each residence.",
    "parent.verification.improvements.title": "Improvement Plan",
    "parent.verification.improvements.desc": "We implement an improvement plan and provide suggestions to increase the quality of each establishment.",
    "parent.community.badge": "COMMUNITY",
    "parent.community.title": "Parent Community",
    "parent.community.subtitle": "Connect with other parents going through the same experience. Share tips, concerns and solutions.",
    "parent.community.forum.title": "Discussion Forum",
    "parent.community.forum.desc": "Participate in conversations about housing, security and university experiences",
    "parent.community.events.title": "Events and Meetups",
    "parent.community.events.desc": "Meet other parents at organized events when you visit your child",
    "parent.community.discounts.title": "Exclusive Discounts",
    "parent.community.discounts.desc": "Access discounts on hotels, transport and services for your visits",
    "parent.points.title": "Points and Badges System",
    "parent.points.subtitle": "Earn benefits while helping other parents and participating in the community",
    "parent.badges.title": "Membership Levels",
    "parent.evaluation.title": "Evaluation and Trust System",
    "parent.evaluation.subtitle": "Understand how the ranking system that protects your child works",
    "parent.evaluation.rankings.title": "Rankings: Beyond Residences",
    "parent.evaluation.rankings.desc": "Rankings aren't just for residences. Students are also evaluated.",
    "parent.resources.title": "Resources for Parents",
    "parent.resources.subtitle": "Everything you need to support your child at this stage",
    "parent.disclaimer.title": "⚠️ Important",
    "parent.disclaimer.text": "Sin Fronteras is a connection and management platform. We are not financial intermediaries nor directly responsible for residence operations. Our function is to verify, connect and facilitate communication between all parties.",

    // Parent Badges
    "parent.badge.newMember": "New Member",
    "parent.badge.newMember.req": "0-50 points",
    "parent.badge.newMember.desc": "Welcome to the community. Start participating and meeting other parents.",
    "parent.badge.newMember.benefit1": "Basic forum access",
    "parent.badge.newMember.benefit2": "View verified residences",
    "parent.badge.collaborator": "Collaborator",
    "parent.badge.collaborator.req": "50-150 points",
    "parent.badge.collaborator.desc": "You're actively participating in the community sharing experiences.",
    "parent.badge.collaborator.benefit1": "5% discount on events",
    "parent.badge.collaborator.benefit2": "Access to private groups",
    "parent.badge.collaborator.benefit3": "Monthly newsletter",
    "parent.badge.active": "Active Member",
    "parent.badge.active.req": "150-350 points",
    "parent.badge.active.desc": "Your participation is valuable. You help other parents with your advice.",
    "parent.badge.active.benefit1": "10% discount on hotels",
    "parent.badge.active.benefit2": "Premium event invitations",
    "parent.badge.active.benefit3": "Priority advisory",
    "parent.badge.expert": "Expert",
    "parent.badge.expert.req": "350-600 points",
    "parent.badge.expert.desc": "You're a reference in the community. Your contributions are highly valued.",
    "parent.badge.expert.benefit1": "15% permanent discount",
    "parent.badge.expert.benefit2": "Group moderator",
    "parent.badge.expert.benefit3": "VIP access to resources",
    "parent.badge.ambassador": "Ambassador",
    "parent.badge.ambassador.req": "600+ points",
    "parent.badge.ambassador.desc": "Maximum level. You represent the best of our parent community.",
    "parent.badge.ambassador.benefit1": "20% lifetime discount",
    "parent.badge.ambassador.benefit2": "Exclusive events",
    "parent.badge.ambassador.benefit3": "Platform decision participation",

    // Parent Resources
    "parent.resource.community.title": "Parent Community",
    "parent.resource.community.desc": "Connect with other parents, share experiences and get advice",
    "parent.resource.security.title": "Security Guide",
    "parent.resource.security.desc": "Everything you need to know about your child's safety",
    "parent.resource.behavior.title": "Behavior Manual",
    "parent.resource.behavior.desc": "Rules and regulations of student residences",
    "parent.resource.discounts.title": "Discounts and Benefits",
    "parent.resource.discounts.desc": "Access to discounts on hotels, transport and tourism services",
    "parent.resource.communication.title": "Communication with Residences",
    "parent.resource.communication.desc": "Direct and transparent contact with residences",
    "parent.resource.support.title": "Support Resources",
    "parent.resource.support.desc": "Practical guides to help your child in university life",

    // Residence PMS Page
    "pms.badge": "PROFESSIONAL MANAGEMENT SYSTEM",
    "pms.hero.title": "PMS for Student Residences",
    "pms.hero.subtitle": "Professionalize your residence with our complete management system. Everything you need in one platform.",
    "pms.hero.demo": "Request Free Demo",
    "pms.hero.pricing": "View Pricing",
    "pms.features.title": "PMS Features",
    "pms.features.subtitle": "Everything you need to manage your residence professionally",
    "pms.features.students.title": "Student Management",
    "pms.features.students.desc": "Register and manage all your residents' information",
    "pms.features.payments.title": "Payment Control",
    "pms.features.payments.desc": "Automatic tracking of payments, installments and late fees",
    "pms.features.maintenance.title": "Maintenance",
    "pms.features.maintenance.desc": "Incident management and maintenance requests",
    "pms.features.docs.title": "Documentation",
    "pms.features.docs.desc": "Secure storage of contracts and legal documents",
    "pms.features.reports.title": "Reports and Statistics",
    "pms.features.reports.desc": "Real-time financial and operational analysis",
    "pms.features.panel.title": "Integrated Panel",
    "pms.features.panel.desc": "Everything you need in one place, easy to use",
    "pms.benefits.title": "System Benefits",
    "pms.benefits.subtitle": "Transform your residence with our comprehensive platform",
    "pms.benefits.sync.title": "Automatic Synchronization",
    "pms.benefits.sync.desc": "Your public profile on the portal is automatically updated from the PMS. Real-time availability without duplicating work. Students see exactly which rooms are available at any time.",
    "pms.benefits.visibility.title": "Greater Visibility",
    "pms.benefits.visibility.desc": "Appear in searches by thousands of verified students and parents. Increase your occupancy up to 40% with our active user base looking for accommodation.",
    "pms.benefits.reputation.title": "Reputation System",
    "pms.benefits.reputation.desc": "Improve your positioning with good ratings and earn up to 20% discount on your monthly plan. Top-rated residences appear first in searches.",
    "pms.benefits.support.title": "24/7 Dedicated Support",
    "pms.benefits.support.desc": "Technical support team available to help you with any questions or problems. Complete training included and constant updates at no additional cost.",
    "pms.points.title": "Points and Badges System",
    "pms.points.subtitle": "Improve your service and get significant discounts on your monthly plan",
    "pms.badges.title": "Certification Levels",
    "pms.evaluation.title": "Bidirectional Evaluation System",
    "pms.evaluation.subtitle": "On our platform, you don't just evaluate: you are also evaluated. A fair system that benefits everyone.",
    "pms.evaluation.improve.title": "Evaluate and Continuously Improve",
    "pms.evaluation.improve.desc": "Rankings aren't just for residences. Students also have scores based on their behavior and coexistence.",
    "pms.evaluation.howTo.title": "How Do You Evaluate Your Residents?",
    "pms.evaluation.howTo.desc": "You can evaluate each student on coexistence concepts. Your opinion, along with that of other roommates, forms the student's score:",
    "pms.evaluation.benefits.title": "System Benefits",
    "pms.evaluation.forResidence": "For Your Residence:",
    "pms.evaluation.forResidence1": "Attract responsible and verified students",
    "pms.evaluation.forResidence2": "Reduce conflicts with prior information",
    "pms.evaluation.forResidence3": "Improve your reputation with positive evaluations",
    "pms.evaluation.forStudents": "For Students:",
    "pms.evaluation.forStudents1": "They know the quality of your residence before booking",
    "pms.evaluation.forStudents2": "Fair system based on real experiences",
    "pms.evaluation.forStudents3": "Incentive to maintain good coexistence",
    "pms.warnings.title": "Enhanced Warning Management",
    "pms.warnings.desc": "If there's a serious problem with a resident, you can register warnings on their profile:",
    "pms.warnings.feature1": "The warning is visible to other residences",
    "pms.warnings.feature2": "The incident detail remains private",
    "pms.warnings.feature3": "Parents receive warning notification",
    "pms.warnings.feature4": "Escalation system for serious cases",
    "pms.warnings.note": "This system protects your residence and the community, maintaining student privacy while communicating relevant information.",
    "pms.resources.title": "Additional Resources",
    "pms.resources.subtitle": "Access verified providers and exclusive services for your residence",
    "pms.resources.providers.title": "Verified Providers",
    "pms.resources.providers.desc": "Access reliable cleaning, maintenance and service providers",
    "pms.resources.accounting.title": "Accounting Advisory",
    "pms.resources.accounting.desc": "Accounting and tax resources to manage your residence",
    "pms.resources.hr.title": "Human Resources",
    "pms.resources.hr.desc": "Guides for hiring staff and managing teams",
    "pms.resources.practices.title": "Best Practices",
    "pms.resources.practices.desc": "Learn from the best residences and continuously improve",
    "pms.cta.title": "Ready to professionalize your residence?",
    "pms.cta.subtitle": "Join the network of verified residences and access thousands of students looking for accommodation",
    "pms.cta.demo": "Request Free Demo",
    "pms.cta.contact": "Contact Sales Team",

    // PMS Badges
    "pms.badge.initial": "Initial",
    "pms.badge.initial.req": "0-100 points",
    "pms.badge.initial.desc": "New residence on the platform. Start building your reputation.",
    "pms.badge.initial.benefit1": "Basic listing",
    "pms.badge.initial.benefit2": "No plan discounts",
    "pms.badge.bronze": "Bronze",
    "pms.badge.bronze.req": "100-300 points | 4.0+ ★",
    "pms.badge.bronze.desc": "Good first evaluations. Your residents are satisfied.",
    "pms.badge.bronze.benefit1": "5% discount on monthly plan",
    "pms.badge.bronze.benefit2": "Visible badge",
    "pms.badge.bronze.benefit3": "Search priority",
    "pms.badge.silver": "Silver",
    "pms.badge.silver.req": "300-600 points | 4.3+ ★",
    "pms.badge.silver.desc": "Excellent reputation. Professional management recognized by the community.",
    "pms.badge.silver.benefit1": "10% permanent discount",
    "pms.badge.silver.benefit2": "Featured in results",
    "pms.badge.silver.benefit3": "Priority support",
    "pms.badge.gold": "Gold",
    "pms.badge.gold.req": "600-1000 points | 4.6+ ★",
    "pms.badge.gold.desc": "Reference residence. Superior quality in all aspects.",
    "pms.badge.gold.benefit1": "15% discount",
    "pms.badge.gold.benefit2": "'Featured' section",
    "pms.badge.gold.benefit3": "Access to ambassador program",
    "pms.badge.platinum": "Platinum",
    "pms.badge.platinum.req": "1000+ points | 4.8+ ★",
    "pms.badge.platinum.desc": "Maximum level of excellence. Role model in the industry.",
    "pms.badge.platinum.benefit1": "20% lifetime discount",
    "pms.badge.platinum.benefit2": "Free premium advertising",
    "pms.badge.platinum.benefit3": "Feature development participation",

    // All Residences Page
    "allResidences.available.title": "Available Residences",
    "allResidences.available.subtitle": "Book now and secure your spot",
    "allResidences.unavailable.title": "Currently Unavailable",
    "allResidences.unavailable.subtitle": "Sign up for the waitlist to receive notifications",
    "allResidences.unavailable.badge": "Unavailable",
    "allResidences.viewInfo": "View full information",
    "allResidences.notify": "Notify me when available",
    "allResidences.waitlist.title": "Waitlist",
    "allResidences.waitlist.desc": "We'll notify you when there's availability at",
    "allResidences.waitlist.tip.title": "💡 Important Tip",
    "allResidences.waitlist.tip.desc": "Complete your student profile for priority. Residences can choose which students to contact based on their profiles, so make sure you have all your information updated.",
    "allResidences.waitlist.roomType": "Room type of interest",
    "allResidences.waitlist.selectType": "Select type",
    "allResidences.waitlist.individual": "Single",
    "allResidences.waitlist.double": "Double",
    "allResidences.waitlist.triple": "Triple",
    "allResidences.waitlist.quadruple": "Quadruple",
    "allResidences.waitlist.email": "Notification email",
    "allResidences.waitlist.join": "Join waitlist",
    "allResidences.waitlist.success": "We'll notify you when there's availability! Complete your profile for priority.",

    // Residence Details Page
    "details.verified": "Verified",
    "details.reviews": "reviews",
    "details.sendQuery": "Send chat query",
    "details.book": "Book",
    "details.about.title": "About the residence",
    "details.services.title": "Services",
    "details.commonAreas.title": "Common areas",
    "details.availability.title": "Room availability",
    "details.room.male": "♂ Male",
    "details.room.female": "♀ Female",
    "details.room.available": "available",
    "details.room.of": "of",
    "details.room.month": "/month",
    "details.room.deposit": "+ Deposit",
    "details.room.enrollment": "+ Enrollment",
    "details.room.meetRoommates": "Meet your roommates",
    "details.room.viewProfile": "View profile →",
    "details.room.emptyBed": "Available bed",
    "details.room.bookThisRoom": "Book this room",
    "details.residents.title": "All Residents",
    "details.residents.viewAll": "View all residents",
    "details.residents.current": "current residents",
    "details.contact.title": "Contact information",
    "details.contact.phone": "Phone",
    "details.contact.phoneHidden": "Visible when booking",
    "details.contact.address": "Address",
    "details.contact.addressHidden": "Visible when booking",
    "details.contact.email": "Contact",
    "details.booking.title": "Book Room",
    "details.chat.title": "Contact Residence",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "es";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};